### ISSUE TITLE
Deploy to google play

### ISSUE THREAD

**Issue by codingchili** [codingchili/enigmatic-mouse#25]

**Comment by IzzySoft** [comment]
And don't forget [F-Droid](https://f-droid.org/) :wink:

PS: Could you attach signed APKs to your releases, please, so users can try them without trouble?

**Comment by codingchili** [comment]
Thanks! good point, will definitely sign the next release :)

**Comment by IzzySoft** [comment]
Great! Please let me know when it's there. I could then take it into [my repo](https://apt.izzysoft.de/fdroid/repo) until you feel ready to go for the "official" repo.

**Comment by codingchili** [comment]
1.0.0 is now deployed to Google Play
[https://play.google.com/store/apps/details?id=com.codingchili.mouse.enigma](https://play.google.com/store/apps/details?id=com.codingchili.mouse.enigma)

The last release is also signed,
[https://github.com/codingchili/enigmatic-mouse/releases](https://github.com/codingchili/enigmatic-mouse/releases)

**Comment by esmoak** [comment]
Is this moving towards official repo? The @IzzySoft repo is spectacular, but would love to see this in regular F-Droid. (Thanks Izzy for all that you do.)

**Comment by IzzySoft** [comment]
As I wrote, I gladly assist :smile: (disclosure: I'm one of the maintainers)

**Comment by codingchili** [comment]
@esmoak yes we are moving to it :) 

Looking into it next week, @IzzySoft 

Opened #45

**Comment by IzzySoft** [comment]
Glad to read, @codingchili – ping me if you need help!
