### ISSUE TITLE
wrong APK at tag 1.2.0?

### ISSUE THREAD

**Issue by IzzySoft** [codingchili/enigmatic-mouse#47]
The APK attached to the 1.2.0 tag identifies as 1.1.0 and has the same versionCode as 1.0.1. Could you please

* check it's the correct APK
* fix versionName (or tag name if it's that)
* always increase `versionCode` as that's what Android tells versions apart by; without that, new versions are not accepted as updates

Thanks!

**Comment by IzzySoft** [comment]
@codingchili any chance to place the correct APK there?

**Comment by codingchili** [comment]
@IzzySoft thanks for the reminder!

The release process for 1.2.1/vc4 is has started.

**Comment by codingchili** [comment]
new release is here;

- https://github.com/codingchili/enigmatic-mouse/releases/tag/1.2.1

**Comment by IzzySoft** [comment]
Thanks! That one looks good.
