### ISSUE TITLE
where to put code for permissions

### ISSUE THREAD

**Issue by Akul2010** [codingchili/enigmatic-mouse#49]
In the readme file, it says to put in the following:
```xml
<uses-permission android:name="android.permission.USE_BIOMETRIC"/>
<uses-permission android:name="android.permission.INTERNET"/>
```
but it doesn't specify where. Where do I put it?

**Comment by shaleenbathla** [comment]
This code is placed in AndroidManifest.xml
You can also search the github repo to reach to this code

**Comment by codingchili** [comment]
@shaleenbathla thanks, 

updated the readme to state that the permissions are enabled by default. closing.
